# Generated by Django 4.2.1 on 2023-05-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('role', models.CharField(choices=[('IGL', 'IGL'), ('Lurk', 'Lurk'), ('Support', 'Support'), ('Entry', 'Entry'), ('AWP', 'AWP'), ('Secondary AWP', 'Secondary AWP')], max_length=20)),
                ('country', models.CharField(max_length=60)),
                ('languages', models.CharField(max_length=200)),
                ('team_experience', models.TextField(max_length=600)),
                ('tournament_experience', models.TextField(max_length=600)),
                ('faceit_esportal_esea', models.TextField(max_length=600)),
                ('discord', models.CharField(max_length=60)),
                ('steam', models.CharField(max_length=60)),
            ],
        ),
    ]
