# Generated by Django 4.2.1 on 2023-05-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_faceit_esportal_esea_post_esea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(choices=[('Albania', 'Albania'), ('Andorra', 'Andorra'), ('Austria', 'Austria'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Bulgaria', 'Bulgaria'), ('Croatia', 'Croatia'), ('Cyprus', 'Cyprus'), ('Czech Republic', 'Czech Republic'), ('Denmark', 'Denmark'), ('Estonia', 'Estonia'), ('Finland', 'Finland'), ('France', 'France'), ('Germany', 'Germany'), ('Greece', 'Greece'), ('Hungary', 'Hungary'), ('Iceland', 'Iceland'), ('Ireland', 'Ireland'), ('Italy', 'Italy'), ('Kosovo', 'Kosovo'), ('Latvia', 'Latvia'), ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Malta', 'Malta'), ('Moldova', 'Moldova'), ('Monaco', 'Monaco'), ('Montenegro', 'Montenegro'), ('Netherlands', 'Netherlands'), ('North Macedonia', 'North Macedonia'), ('Norway', 'Norway'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Romania', 'Romania'), ('Russia', 'Russia'), ('San Marino', 'San Marino'), ('Serbia', 'Serbia'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('Spain', 'Spain'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Ukraine', 'Ukraine'), ('United Kingdom', 'United Kingdom'), ('Vatican City', 'Vatican City')], max_length=22),
        ),
        migrations.AlterField(
            model_name='post',
            name='esea',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='esportal',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='faceit',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
