# Generated by Django 4.2.1 on 2023-05-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_country_alter_post_esea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='steam',
            field=models.URLField(max_length=100),
        ),
    ]
