# Generated by Django 4.2.1 on 2023-05-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_steam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='languages',
            field=models.CharField(max_length=56),
        ),
    ]
